export const metadata = {
  title: 'Terms & Conditions | AfterALevel.com',
  description: 'Terms and Conditions for using AfterALevel.com.',
};

export default function TermsConditionsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 pt-24 pb-32">
      <h1 className="text-4xl md:text-5xl font-serif mb-8 text-text-primary">Terms & Conditions</h1>
      <div className="prose prose-slate dark:prose-invert prose-p:text-text-secondary prose-headings:text-text-primary max-w-none">
        <p className="text-sm italic">Last updated: June 22, 2026</p>

        <p>Welcome to AfterALevel.com!</p>

        <p>
          These terms and conditions outline the rules and regulations for the use of AfterALevel.com's Website, located at https://afteralevel.com.
        </p>

        <p>
          By accessing this website we assume you accept these terms and conditions. Do not continue to use AfterALevel.com if you do not agree to take all of the terms and conditions stated on this page.
        </p>

        <h2>License</h2>
        <p>
          Unless otherwise stated, AfterALevel.com and/or its licensors own the intellectual property rights for all material on AfterALevel.com. All intellectual property rights are reserved. You may access this from AfterALevel.com for your own personal use subjected to restrictions set in these terms and conditions.
        </p>

        <p>You must not:</p>
        <ul>
          <li>Republish material from AfterALevel.com</li>
          <li>Sell, rent or sub-license material from AfterALevel.com</li>
          <li>Reproduce, duplicate or copy material from AfterALevel.com</li>
          <li>Redistribute content from AfterALevel.com</li>
        </ul>

        <h2>Disclaimer Regarding Tools and Calculations</h2>
        <p>
          The calculators and tools provided on AfterALevel.com (including but not limited to the UCAS Points Calculator, Grade Predictor, and GPA Converter) are designed to provide estimates and guidance for students. 
        </p>
        <p>
          <strong>No Guarantee of Accuracy:</strong> While we strive to keep our calculations up to date with the latest official standards (such as UCAS Tariff tables), we make no warranties or representations regarding the accuracy, completeness, or reliability of the results generated by our tools.
        </p>
        <p>
          <strong>Not Official Advice:</strong> The results provided by our tools do not constitute official academic or admissions advice. Universities and educational institutions reserve the right to make final decisions regarding admissions, tariff points, and grade equivalencies. You should always verify requirements directly with the institution you are applying to.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          In no event shall AfterALevel.com, nor any of its officers, directors and employees, be held liable for anything arising out of or in any way connected with your use of this Website whether such liability is under contract. AfterALevel.com, including its officers, directors and employees shall not be held liable for any indirect, consequential or special liability arising out of or in any way related to your use of this Website.
        </p>

        <h2>Hyperlinking to our Content</h2>
        <p>
          The following organizations may link to our Website without prior written approval:
        </p>
        <ul>
          <li>Government agencies;</li>
          <li>Search engines;</li>
          <li>News organizations;</li>
          <li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses;</li>
        </ul>
        <p>
          These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party's site.
        </p>

        <h2>Modifications</h2>
        <p>
          AfterALevel.com may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.
        </p>
      </div>
    </main>
  );
}
